### ISSUE TITLE
Header Errors

### ISSUE THREAD

**Issue by mzdebo** [gupta977/flexi#1]
I was looking through the WP plugins found your other plugin, UPG – User Post Gallery and was going to purchase it but I tried the free version and couldn't get it to work with my theme and noticed it hasn't been tested with Wordpress 5.4. Then I seen this plugin and it looked more fitting to my needs, but there's a small problem when installing it.

After installing the plugin and then hitting the activate button it gives an error message 'The plugin does not have a valid header.' 

I have the WP debug showing my logs but it doesn't give any other errors. If I go to the wp-admin/plugins area it shows it installed, but not activated, and when I hit the activate button in the plugin list it activates with no other errors. 

 So the plugin can still be activated from the list of plugins, but not directly after installation. The page has to be refreshed.

I'm by no means a coder or developer, but I study others works and dabble a bit. With that said I looked at your code ... 

Is it possible that these files are causing Wordpress to get confused because these include a plugin header comment also?

block/plugin.php
includes/cmb2/init.php

From what I've seen in other plugins these lines below should be reserved for the mandatory header comment of plugin main file. 

/*
Plugin Name: ...
Plugin URI: ...
Author: ...
*/

I probably would reference/include it in the php files it as follows:

/**
 * Bootstraps the CMB2 process
 *
 * @category  WordPress_Plugin
 * @package   CMB2
 * @author    CMB2
 * @license   GPL-2.0+
 * @link      https://cmb2.io
 */

If you don't mind I forked this, changed the the two files I mentioned above, uploaded it to my Wordpress, activated it normally and it worked. I don't know if this is the problem but I thought I'd at least give you me thoughts. 

Good Luck

**Comment by gupta977** [comment]
Yes, I got several report about this error but not able to find the exact location for it.
You said you FORK it, but I don't see any changes.
Your help will be appreciated.

**Comment by gupta977** [comment]
I have updated the new version, please have a look and let me know if it
gets fixed.

**Comment by mzdebo** [comment]
I did test it out with a fresh install the update works perfectly now. So the header error is gone. 

Sorry I know how to fork but I haven't learned yet to actually use it once it's forked to make changes.

**Comment by gupta977** [comment]
I have updated so many time but still some are reporting error during activation. 
Can you have a look again ?
